### ISSUE TITLE
Maven and Ant builds both fail - problem perhaps me

### ISSUE THREAD

**Issue by mlevison** [gdinwiddie/EquineHoroscope#2]
George - in attempt to follow your excellent experiment from the comfort of my own home, I pulled down your repo. 

Several reflections and discoveries:
- I imported the project as a Maven build (effectively: http://stackoverflow.com/questions/14896152/how-to-build-and-run-maven-projects-after-importing-into-eclipse-ide) - I wasn't sure if this was your intention
- I tried to run the maven build and it failed on in attempt to find 3 jars (logs below)
- I decide to fallback to Ant. It failed even faster (and we do admire fail fast in this industry :-)

Please appreciate since I no longer code full time, I've managed to ignore maven for a few years. This means the problem is probably PEBCAK

Thanks in advance
Mark - your friend in whiskey, beer and wine

---Maven's log
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.gdinwiddie:equine_horoscope:jar:0.0.1
[WARNING] 'dependencies.dependency.systemPath' for main:moco-runner:jar should not point at files within the project directory, ${project.basedir}/lib/moco-runner-0.11.0-SNAPSHOT-uber.jar will be unresolvable by dependent projects @ line 83, column 16
[WARNING] 'dependencies.dependency.systemPath' for main:idiaJdbc:jar should not point at files within the project directory, ${project.basedir}/lib/idiaJdbc.jar will be unresolvable by dependent projects @ line 91, column 16
[WARNING] 'dependencies.dependency.systemPath' for main:mumbler:jar should not point at files within the project directory, ${project.basedir}/lib/mumbler.jar will be unresolvable by dependent projects @ line 99, column 16
[WARNING] 'dependencies.dependency.systemPath' for main:moco-runner:jar refers to a non-existing file /Users/mlevison/git/Java/EquineHoroscope/lib/moco-runner-0.11.0-SNAPSHOT-uber.jar @ line 83, column 16
[WARNING] 'dependencies.dependency.systemPath' for main:idiaJdbc:jar refers to a non-existing file /Users/mlevison/git/Java/EquineHoroscope/lib/idiaJdbc.jar @ line 91, column 16
[WARNING] 'dependencies.dependency.systemPath' for main:mumbler:jar refers to a non-existing file /Users/mlevison/git/Java/EquineHoroscope/lib/mumbler.jar @ line 99, column 16
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.135 s
[INFO] Finished at: 2016-03-28T16:22:41-04:00
[INFO] Final Memory: 7M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException

----Ant Build Failure
Buildfile: /Users/mlevison/git/Java/EquineHoroscope/build.xml
classpath:
compile:
    [javac] Compiling 25 source files to /Users/mlevison/git/Java/EquineHoroscope/target/classes

BUILD FAILED
/Users/mlevison/git/Java/EquineHoroscope/build.xml:46: /Users/mlevison/git/Java/EquineHoroscope/lib does not exist.

Total time: 349 milliseconds

**Comment by wouterla** [comment]
Hi Mark,

You'll need George's libs zip file: [http://idiacomputing.com/pub/EquineHoroscopeJars.zip](http://idiacomputing.com/pub/EquineHoroscopeJars.zip) unzipped into the project dir.

The ant build should run, though I think you'll still get an error from the loading of a json file. Command-line operation doesn't really work out-of-the-box. 

I think George's intention is to get people to import the project as an existing eclipse project. He checked in the eclipse metadata files so it should be fully up-and-running. 

To run on command-line, just change the loading of the json file to use a resource instead of directly loading a file:

In LocalhostJsonMerchantBankAdapterTest.java change the line:

server = jsonHttpServer(12345, file("bin/com/gdinwiddie/creditcardprocessor/merchantbank/moco_config.json"));

to:

server = jsonHttpServer(12345, pathResource("com/gdinwiddie/creditcardprocessor/merchantbank/moco_config.json"));

And also add the correct static import.

And things should work from ant. For maven, I made a few additional changes to the pom.xml, let me know if you need them.

**Comment by gdinwiddie** [comment]
Mark, sorry for the difficulty. I've been focusing on making things work in Eclipse, as that's the most immediate for a workshop. I've occasionally fixed the Maven build, which I seem to break without noticing since I'm not running a CI build server. I kinda gave up on maintaining the Ant build, but it should work with all of the jars unzipped into the lib directory.

Grab the jars and let me know what problems remain.

**Comment by gdinwiddie** [comment]
I've just pushed the pathResource change to master. I don't know why it didn't work when I tried it before, but it's working fine now.

The Ant build runs for me, but only runs the Cucumber features by default. It needs work to run the unit tests.

**Comment by wouterla** [comment]
I'm adding a few things to the maven build to run the dependencies. I'll also check the ant build.

**Comment by gdinwiddie** [comment]
Wouter, I merged your pull request, but the ant junit tests fail for me. Are they working for you?

**Comment by gdinwiddie** [comment]
The Maven build works, even under Travis CI. If you look at the .travis.yml file, you'll see I'm using wget and unzip to install the jars in the lib directory prior to the build.

**Comment by mlevison** [comment]
Caveat - it may just have been the jars. I really did just want to use
Eclipse, I went down the rabbit hole or maven/ant when a straight eclipse
import wasn't working.

Back to planning a birthday party.

Cheers
Mark

On Mon, Mar 28, 2016 at 5:09 PM, Wouter Lagerweij notifications@github.com
wrote:

> Hi Mark,
> 
> You'll need George's libs zip file:
> http://idiacomputing.com/pub/EquineHoroscopeJars.zip unzipped into the
> project dir.
> 
> The ant build should run, though I think you'll still get an error from
> the loading of a json file. Command-line operation doesn't really work
> out-of-the-box.
> 
> I think George's intention is to get people to import the project as an
> existing eclipse project. He checked in the eclipse metadata files so it
> should be fully up-and-running.
> 
> To run on command-line, just change the loading of the json file to use a
> resource instead of directly loading a file:
> 
> In LocalhostJsonMerchantBankAdapterTest.java change the line:
> 
> server = jsonHttpServer(12345,
> file("bin/com/gdinwiddie/creditcardprocessor/merchantbank/moco_config.json"));
> 
> to:
> 
> server = jsonHttpServer(12345,
> pathResource("com/gdinwiddie/creditcardprocessor/merchantbank/moco_config.json"));
> 
> And things should work from ant. For maven, I made a few additional
> changes to the pom.xml, let me know if you need them.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gdinwiddie/EquineHoroscope/issues/2#issuecomment-202581877

## 

[image: headshot-square-300x300]
http://www.flickr.com/photos/36331075@N00/9674877046/ _Mark Levison_ | 1
(877) 248-8277 | Twitter https://twitter.com/mlevison | LinkedIn
http://ca.linkedin.com/in/marklevison | Facebook
https://www.facebook.com/agilepainrelief
Certified ScrumMaster Training: Vancouver
http://agilepainrelief.com/courses/vancouver | Edmonton
http://agilepainrelief.com/courses/edmonton | Ottawa
http://agilepainrelief.com/courses/ottawa | Montreal
http://agilepainrelief.com/courses/montreal | Toronto
http://agilepainrelief.com/courses/toronto
Certified Product Owner & Private Training also available ~ Our Training
Schedule http://agilepainrelief.com/courses/certified-scrum-agile-training
Agile Pain Relief Consulting http://agilepainrelief.com/ | Notes from a
Tool User http://agilepainrelief.com/notesfromatooluser
Proud Sponsor of Agile Tour Gatineau Ottawa http://goagiletour.ca/ and Agile
Coach Camp Canada http://agilecoachcampcanada.wordpress.com/

**Comment by wouterla** [comment]
George, I've done a '`reset --hard origin/HEAD`', re-added the latest jars zip, and both '`ant`' (including all junit tests) and '`mvn clean install`' work for me in that state.

Manually (or with separate script) downloading the lib dir is fine. I'd still prefer using the local_repo setup (perhaps downloaded as now instead of checked in), as generating the lib dir with maven should mean that you get all transitive dependencies as well, limiting possible surprises during an off-line workshop.

Having Travis is nice, that should help keep things running!

I'm always very keen on getting things working on the command-line myself, feel free to ignore all that of course. I do think that fewer people will have eclipse nowadays, so I'd want to make sure there's a fallback.

**Comment by mlevison** [comment]
George and Wouter - thanks for the help so far. My passionate dislike of
all things Eclipse/Maven grows. This is one of the reasons I fear trying to
run a course where I use anything that isn't installed with Eclipse.

Part of what slays me with Eclipse - there is never one obvious clear way
of achieving things. Instead there are always 6 bad looking options

My tale of woe (or whiskey?)
1. Delete the existing workspace from eclipse
2. Unzip the Equine Library file
3. Confirm the infamous 3 dependencies mentioned by maven are in the
   folder
4. Import the project back into Eclipse
5. Eclipse complains that it can't find a bunch of libraries *<-----
   This is my moment of crisis - > *My libraries are
   in /Users/mlevison/git/Java/EquineHoroscope/lib but Eclipse thought it was
   looking in: /EquineHoroscope/lib
   - Do I manually change every library reference? via
     ConfigureBuildPath... -> Libraries Tab?
   - Run Maven
   - Do something clever I couldn't find?
6. I tried Maven and we're back to the errors that I raised the first
   time

[INFO] Scanning for projects...

[WARNING]

[WARNING] Some problems were encountered while building the effective model
for com.gdinwiddie:equine_horoscope:jar:0.0.1

[WARNING] 'dependencies.dependency.systemPath' for main:moco-runner:jar
should not point at files within the project directory,
${project.basedir}/lib/moco-runner-0.11.0-SNAPSHOT-uber.jar will be
unresolvable by dependent projects @ line 83, column 16

[WARNING] 'dependencies.dependency.systemPath' for main:idiaJdbc:jar should
not point at files within the project directory,
${project.basedir}/lib/idiaJdbc.jar will be unresolvable by dependent
projects @ line 91, column 16

[WARNING] 'dependencies.dependency.systemPath' for main:mumbler:jar should
not point at files within the project directory,
${project.basedir}/lib/mumbler.jar will be unresolvable by dependent
projects @ line 99, column 16

[WARNING]

[WARNING] It is highly recommended to fix these problems because they
threaten the stability of your build.

[WARNING]

[WARNING] For this reason, future Maven versions might no longer support
building such malformed projects.

[WARNING]

## [INFO]

[INFO] BUILD FAILURE

## [INFO]

[INFO] Total time: 0.120 s

[INFO] Finished at: 2016-03-29T10:17:17-04:00

[INFO] Final Memory: 7M/245M

## [INFO]

[image: Inline image 1]

Yet as the above Screenshot should prove (assuming it came through) the jar
files are in the lib directory.

Confused in Ottawa

Mark

On Mon, Mar 28, 2016 at 10:25 PM, Wouter Lagerweij <notifications@github.com

> wrote:
> 
> George, I've done a 'reset --hard origin/HEAD', re-added the latest jars
> zip, and both 'ant' (including all junit tests) and 'mvn clean install'
> work for me in that state.
> 
> Manually (or with separate script) downloading the lib dir is fine. I'd
> still prefer using the local_repo setup (perhaps downloaded as now instead
> of checked in), as generating the lib dir with maven should mean that you
> get all transitive dependencies as well, limiting possible surprises during
> an off-line workshop.
> 
> Having Travis is nice, that should help keep things running!
> 
> I'm always very keen on getting things working on the command-line myself,
> feel free to ignore all that of course. I do think that fewer people will
> have eclipse nowadays, so I'd want to make sure there's a fallback.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gdinwiddie/EquineHoroscope/issues/2#issuecomment-202671282

## 

[image: headshot-square-300x300]
http://www.flickr.com/photos/36331075@N00/9674877046/ _Mark Levison_ | 1
(877) 248-8277 | Twitter https://twitter.com/mlevison | LinkedIn
http://ca.linkedin.com/in/marklevison | Facebook
https://www.facebook.com/agilepainrelief
Certified ScrumMaster Training: Vancouver
http://agilepainrelief.com/courses/vancouver | Edmonton
http://agilepainrelief.com/courses/edmonton | Ottawa
http://agilepainrelief.com/courses/ottawa | Montreal
http://agilepainrelief.com/courses/montreal | Toronto
http://agilepainrelief.com/courses/toronto
Certified Product Owner & Private Training also available ~ Our Training
Schedule http://agilepainrelief.com/courses/certified-scrum-agile-training
Agile Pain Relief Consulting http://agilepainrelief.com/ | Notes from a
Tool User http://agilepainrelief.com/notesfromatooluser
Proud Sponsor of Agile Tour Gatineau Ottawa http://goagiletour.ca/ and Agile
Coach Camp Canada http://agilecoachcampcanada.wordpress.com/

**Comment by wouterla** [comment]
Can't see the images, Mark...

And there's no errors in your maven output, just warnings and then a build failure, which is strange.

If I do the following, I have a working maven, ant and eclipse:

git clone git@github.com:gdinwiddie/EquineHoroscope.git test
cd test
unzip ~/Downloads/EquineHoroscopeJars\ (2).zip 
mvn clean install
ant

For the eclipse part:
mvn eclipse:eclipse
(start eclipse, import existing project using default settings)
(I had to override project settings for Java compiler to allow jdk 1.8 sources)
right-click project, run as... maven install (probably assumes m2eclipse plugin, not sure it that's there by default)

**Comment by gdinwiddie** [comment]
Mark,

On 3/29/16 10:43 AM, mlevison wrote:

> George and Wouter - thanks for the help so far. My passionate dislike of
> all things Eclipse/Maven grows. This is one of the reasons I fear trying to
> run a course where I use anything that isn't installed with Eclipse.
> 
> Part of what slays me with Eclipse - there is never one obvious clear way
> of achieving things. Instead there are always 6 bad looking options
> 
> My tale of woe (or whiskey?)
> 1. Delete the existing workspace from eclipse
> 2. Unzip the Equine Library file
> 3. Confirm the infamous 3 dependencies mentioned by maven are in the
>    folder
> 4. Import the project back into Eclipse
> 5. Eclipse complains that it can't find a bunch of libraries *<-----
>    This is my moment of crisis - > *My libraries are
>    in /Users/mlevison/git/Java/EquineHoroscope/lib but Eclipse thought it was
>    looking in: /EquineHoroscope/lib
> 6. Do I manually change every library reference? via
>    ConfigureBuildPath... -> Libraries Tab?

I would delete the current library references via ConfigureBuildPath and 
then use the Add JARs button to add them all in at one swoop.
- George

## 

---
- George Dinwiddie \*                             iDIA Computing, LLC
  Software Development                    http://www.idiacomputing.com
  Consultant and Coach                      http://blog.gdinwiddie.com
  ----------------------------------------------------------------------

**Comment by mlevison** [comment]
George - that worked.

Caveat - I pulled a clean copy of source and had to delete out all the
references to the /EquineHoroscope/lib - from the list of jars. Before you
hand this to victims (students?) you might try pulling in a clean version
yourself just to see what happens :-)

Go ahead and close this issue. Now I just have to figure what to run.

Cheers
Mark

On Tue, Mar 29, 2016 at 11:45 AM, George Dinwiddie <notifications@github.com

> wrote:
> 
> Mark,
> 
> On 3/29/16 10:43 AM, mlevison wrote:
> 
> > George and Wouter - thanks for the help so far. My passionate dislike of
> > all things Eclipse/Maven grows. This is one of the reasons I fear trying
> > to
> > run a course where I use anything that isn't installed with Eclipse.
> > 
> > Part of what slays me with Eclipse - there is never one obvious clear way
> > of achieving things. Instead there are always 6 bad looking options
> > 
> > My tale of woe (or whiskey?)
> > 1. Delete the existing workspace from eclipse
> > 2. Unzip the Equine Library file
> > 3. Confirm the infamous 3 dependencies mentioned by maven are in the
> >    folder
> > 4. Import the project back into Eclipse
> > 5. Eclipse complains that it can't find a bunch of libraries *<-----
> >    This is my moment of crisis - > *My libraries are
> >    in /Users/mlevison/git/Java/EquineHoroscope/lib but Eclipse thought it
> >    was
> >    looking in: /EquineHoroscope/lib
> > 6. Do I manually change every library reference? via
> >    ConfigureBuildPath... -> Libraries Tab?
> 
> I would delete the current library references via ConfigureBuildPath and
> then use the Add JARs button to add them all in at one swoop.
> - George
> 
> ## 
> 
> ---
> - George Dinwiddie \* iDIA Computing, LLC
>   Software Development http://www.idiacomputing.com
>   Consultant and Coach http://blog.gdinwiddie.com
>   ----------------------------------------------------------------------
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/gdinwiddie/EquineHoroscope/issues/2#issuecomment-202967956

## 

[image: headshot-square-300x300]
http://www.flickr.com/photos/36331075@N00/9674877046/ _Mark Levison_ | 1
(877) 248-8277 | Twitter https://twitter.com/mlevison | LinkedIn
http://ca.linkedin.com/in/marklevison | Facebook
https://www.facebook.com/agilepainrelief
Certified ScrumMaster Training: Vancouver
http://agilepainrelief.com/courses/vancouver | Edmonton
http://agilepainrelief.com/courses/edmonton | Ottawa
http://agilepainrelief.com/courses/ottawa | Montreal
http://agilepainrelief.com/courses/montreal | Toronto
http://agilepainrelief.com/courses/toronto
Certified Product Owner & Private Training also available ~ Our Training
Schedule http://agilepainrelief.com/courses/certified-scrum-agile-training
Agile Pain Relief Consulting http://agilepainrelief.com/ | Notes from a
Tool User http://agilepainrelief.com/notesfromatooluser
Proud Sponsor of Agile Tour Gatineau Ottawa http://goagiletour.ca/ and Agile
Coach Camp Canada http://agilecoachcampcanada.wordpress.com/
